name: Run unit tests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test_on_wasm:
    name: Build and Test on WebAssembly
    runs-on: Ubuntu-22.04
    container:
      image: ghcr.io/swiftwasm/carton:latest
    steps:
      - uses: actions/checkout@v4
      - run: carton test
  test_on_Linux:
    name: Build and Test on Linux
    strategy:
      matrix:
        swift-version: ["5.1", "5.2", "5.3", "5.4", "5.5", "5.6", "5.7", "5.8", "5.9"]
    runs-on: ubuntu-20.04
    env:
      # Workaround for node issue. See https://github.com/actions/checkout/issues/1590
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    container:
      image: swift:${{ matrix.swift-version }}
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - run: swift test --enable-test-discovery
  test_on_macOS-14:
    name: Build and Test on macOS-14
    strategy:
      matrix:
        xcode-version:
          - /Applications/Xcode_15.4.app
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s "${{ matrix.xcode-version }}"
      - run: swift --version
      - run: swift test
  test_on_macOS-13:
    name: Build and Test on macOS-13
    strategy:
      matrix:
        xcode-version:
          - /Applications/Xcode_14.3.1.app
    runs-on: macOS-13
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s "${{ matrix.xcode-version }}"
      - run: swift --version
      - run: swift test
  test_on_macOS-12:
    name: Build and Test on macOS
    strategy:
      matrix:
        xcode-version:
          - /Applications/Xcode_13.4.app
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -s "${{ matrix.xcode-version }}"
      - run: swift --version
      - run: swift test
  coverage:
    name: Collect test coverage
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - run: xcodebuild -scheme StubKit -project StubKit.xcodeproj -sdk macosx -enableCodeCoverage YES build test
      - uses: codecov/codecov-action@v1
